# Generated by Django 2.2 on 2020-07-31 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='descripcion', verbose_name='Resumen'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.TextField(max_length=300, unique=True, verbose_name='Titulo'),
        ),
    ]
