# Generated by Django 2.2 on 2020-07-31 19:49

from django.db import migrations, models
import repository.models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20200730_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='file',
            field=models.FileField(default='empty.pdf', upload_to='./files', validators=[repository.models.validate_pdf], verbose_name='Archivo PDF'),
            preserve_default=False,
        ),
    ]
