# Generated by Django 2.2 on 2020-08-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_project_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='autor',
            field=models.CharField(default='Elias Colmenarez', max_length=60, verbose_name='Autor'),
            preserve_default=False,
        ),
    ]
