# Generated by Django 2.2 on 2020-08-23 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_project_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='autor',
            new_name='author',
        ),
    ]
