# Generated by Django 2.2 on 2020-08-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_auto_20200823_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='lastname',
        ),
        migrations.AlterField(
            model_name='tutor',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre y Apellido'),
        ),
    ]
