# Generated by Django 2.2 on 2020-08-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_auto_20200824_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='lastname',
            field=models.CharField(default='borrar', max_length=50, verbose_name='Nombre y Apellido'),
            preserve_default=False,
        ),
    ]
