# Generated by Django 2.2 on 2020-08-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_tutor_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tutor',
            field=models.ForeignKey(on_delete=models.SET('EMPTY'), to='repository.Tutor'),
        ),
    ]
