# Generated by Django 2.2 on 2020-08-24 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0008_auto_20200824_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tutor',
            field=models.ForeignKey(on_delete=models.SET(0), to='repository.Tutor'),
        ),
    ]
