# Generated by Django 2.2 on 2020-09-23 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='img',
            field=models.ImageField(help_text='(200X300px recomendado)', upload_to='employees', verbose_name='Foto'),
        ),
    ]
