# Generated by Django 2.2 on 2020-09-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20200922_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Identificador del contacto', max_length=50, verbose_name='Nombre')),
                ('email', models.EmailField(blank=True, help_text='Ejemplo@gmail.com', max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, help_text='0251-1234567', max_length=50, null=True, verbose_name='Telefono')),
            ],
            options={
                'verbose_name': 'Contacto',
            },
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Empleado'},
        ),
    ]
